### PR TITLE
feat: upgrade dependencies and tooling

### PR DESCRIPTION
**Pull request by e0ipso**

### CODE REVIEW

**Comment by nyl-auster** [comment]
@e0ipso thx ! tooling + upgrade + prettier = ❤️

Can you explain hre the benefits about creating a sub "frontend" directory : 
- this is only a frontend project, so a "frontend" seems redundant
- this is not what the standard installation of Nuxt is doing ( even if i would like him to avec a "src" directory but sticking with what Nuxt is doing sounds logical )

Are we putting contentajs in this repo too ? 
Or is this to have only on and same between a future *contentajs_vue_nuxt* and *contenta_vue_nuxt* ?

**Comment by e0ipso** [comment]
I think we clarified most of the points in Slack. I like your idea of renaming `frontend` to `src`. I'll do that soon.

**Comment by nyl-auster** [comment]
@e0ipso sorry my english is not so good and I did not actually understand on Slack why it is needed to create a sub-directory and not leave the original Nuxt structure as it is; if contentajs is in another repo.

**Comment by e0ipso** [comment]
No worries. The main idea is to make sure we can make the Nuxt app work in a subdirectory. This is not an uncommon requirement if you have a monorepo code architecture.

**Comment by nyl-auster** [comment]
@e0ipso i'm not worrying, I was  just trying to understand ( it can already work as it is with a mono repo architecture, isn't it ? ). Waiting for you to rename "front-end" to  "src".

**Comment by e0ipso** [comment]
_No worries_ is an expression usually used when someone says _sorry_ but you don't think that he needs to be sorry.

---

My goal is to make sure we have a good example to set up with a subfolder. I say that because I tried to do it and it was not easy. Others may try to do it as well, so we have the chance to help them.

Does that make sense?

**Comment by nyl-auster** [comment]
@e0ipso nope, as I said, that doest not makes much sense for me ^^  

Contenta_vue_nuxt was designed to have a very low barrier entry with a very simple structure for beginners and not to solve this kind of issues with subfolder; or to add complexity with a nodejs proxy.  I just wanted people to try and understand very very easily decoupled.

Using another structure than the one you have when downloading Nuxt or looking at its documentation is a no-go for me. 

So this is not anymore what I worked for and i'm pretty sad. Feel free to do what ever you want on this project, Contenta is your baby after all :)

**Pull request merged**
